const ProductApi = [
    {
        _id : '1',
        name:'mobile',
        description:'ver coll product',
        image:'/images/banner2.jpg',
        brand:'samsung',
        category:'electronics',
        price:3456,
        countinstock:13,
        rating:4.5,
        numReviews:12,
    },
    {
        _id : '2',
        name:'mobile',
        description:'ver coll product',
        image:'/images/banner2.jpg',
        brand:'samsung',
        category:'electronics',
        price:3456,
        countinstock:13,
        rating:5.4,
        numReviews:12,
    },
    {
        _id : '3',
        name:'mobile',
        description:'ver coll product',
        image:'/images/banner2.jpg',
        brand:'samsung',
        category:'electronics',
        price:3456,
        countinstock:13,
        rating:5.4,
        numReviews:12,
    },
    {
        _id : '4',
        name:'mobile',
        description:'ver coll product',
        image:'/images/banner2.jpg',
        brand:'samsung',
        category:'electronics',
        price:3456,
        countinstock:13,
        rating:5.4,
        numReviews:12,
    },
    {
        _id : '5',
        name:'mobile',
        description:'ver coll product',
        image:'/images/banner2.jpg',
        brand:'samsung',
        category:'electronics',
        price:3456,
        countinstock:13,
        rating:5.4,
        numReviews:12,
    },
    {
        _id : '6',
        name:'mobile',
        description:'ver coll product',
        image:'/images/banner2.jpg',
        brand:'samsung',
        category:'electronics',
        price:3456,
        countinstock:13,
        rating:5.4,
        numReviews:12,
    },
]
export default ProductApi ;